### ISSUE TITLE
Collaborator assignment 

### ISSUE THREAD

**Issue by hagankristen** [Duke-BME-Design/LaserEye_testing#2]
GitHub won't recognize me as a collaborator since the commits are under my "kristenhagan@DESKTOP-F6L9VU9:@localhost" address and not my account email. How can I fix this? I don't know how to verify this email address with GitHub.

**Comment by mlp6** [comment]
Not exactly sure what the issue is with recognizing the username correctly, but you can control what git uses as your username by running through the `git config --global user.name` command (https://help.github.com/articles/setting-your-username-in-git/).  Let us know if that helps.

**Comment by hagankristen** [comment]
I'm not sure how to test if that worked. I manually claimed that the commits for the sum function as mine and it seems like its fine?

**Comment by mlp6** [comment]
LGTM!
